routes:
  /:
    as: addons.happy-dates
    uses: HappyDatesController@index
  /edit/{event}:
    as: addons.happydates.edit
    uses: HappyDatesController@edit
  /create:
    as: addons.happy-dates.create
    uses: HappyDatesController@create
  post@store:
    as: addons.happy-dates.store
    uses: HappyDatesController@store
  post@update:
    as: addons.happy-dates.update
    uses: HappyDatesController@update
  delete@destroy:
    as: addons.happy-dates.destroy
    uses: HappyDatesController@destroy
  delete@destroy_entries:
    as: addons.happy-dates.destroy_entries
    uses: HappyDatesController@destroy_entries
  /refreshAll:
    as: addons.happy-dates.refreshAll
    uses: HappyDatesController@refreshAll
