routes:
  /:
    as: addons.icalimport
    uses: IcalImportController@index
  /edit/{event}:
    as: addons.icalimport.edit
    uses: IcalImportController@edit
  /create:
    as: addons.icalimport.create
    uses: IcalImportController@create
  post@store:
    as: addons.icalimport.store
    uses: IcalImportController@store
  post@update:
    as: addons.icalimport.update
    uses: IcalImportController@update
  delete@destroy:
    as: addons.icalimport.destroy
    uses: IcalImportController@destroy
  /refreshAll:
    as: addons.icalimport.refreshAll
    uses: IcalImportController@refreshAll
